%% push value
-define(                   '0', 16#00).
-define(           'PUSHDATA1', 16#4c).
-define(           'PUSHDATA2', 16#4d).
-define(           'PUSHDATA4', 16#4e).
-define(             '1NEGATE', 16#4f).
-define(            'RESERVED', 16#50).
-define(                   '1', 16#51).
-define(                   '2', 16#52).
-define(                   '3', 16#53).
-define(                   '4', 16#54).
-define(                   '5', 16#55).
-define(                   '6', 16#56).
-define(                   '7', 16#57).
-define(                   '8', 16#58).
-define(                   '9', 16#59).
-define(                  '10', 16#5a).
-define(                  '11', 16#5b).
-define(                  '12', 16#5c).
-define(                  '13', 16#5d).
-define(                  '14', 16#5e).
-define(                  '15', 16#5f).
-define(                  '16', 16#60).

%% control
-define(                 'NOP', 16#61).
-define(                 'VER', 16#62).
-define(                  'IF', 16#63).
-define(               'NOTIF', 16#64).
-define(               'VERIF', 16#65).
-define(            'VERNOTIF', 16#66).
-define(                'ELSE', 16#67).
-define(               'ENDIF', 16#68).
-define(              'VERIFY', 16#69).
-define(              'RETURN', 16#6a).

%% stack ops
-define(          'TOALTSTACK', 16#6b).
-define(        'FROMALTSTACK', 16#6c).
-define(               '2DROP', 16#6d).
-define(                '2DUP', 16#6e).
-define(                '3DUP', 16#6f).
-define(               '2OVER', 16#70).
-define(                '2ROT', 16#71).
-define(               '2SWAP', 16#72).
-define(               'IFDUP', 16#73).
-define(               'DEPTH', 16#74).
-define(                'DROP', 16#75).
-define(                 'DUP', 16#76).
-define(                 'NIP', 16#77).
-define(                'OVER', 16#78).
-define(                'PICK', 16#79).
-define(                'ROLL', 16#7a).
-define(                 'ROT', 16#7b).
-define(                'SWAP', 16#7c).
-define(                'TUCK', 16#7d).

%% splice ops
-define(                 'CAT', 16#7e).
-define(              'SUBSTR', 16#7f).
-define(                'LEFT', 16#80).
-define(               'RIGHT', 16#81).
-define(                'SIZE', 16#82).

%% bit logic
-define(              'INVERT', 16#83).
-define(                 'AND', 16#84).
-define(                  'OR', 16#85).
-define(                 'XOR', 16#86).
-define(               'EQUAL', 16#87).
-define(         'EQUALVERIFY', 16#88).
-define(           'RESERVED1', 16#89).
-define(           'RESERVED2', 16#8a).

%% numeric
-define(                '1ADD', 16#8b).
-define(                '1SUB', 16#8c).
-define(                '2MUL', 16#8d).
-define(                '2DIV', 16#8e).
-define(              'NEGATE', 16#8f).
-define(                 'ABS', 16#90).
-define(                 'NOT', 16#91).
-define(           '0NOTEQUAL', 16#92).
-define(                 'ADD', 16#93).
-define(                 'SUB', 16#94).
-define(                 'MUL', 16#95).
-define(                 'DIV', 16#96).
-define(                 'MOD', 16#97).
-define(              'LSHIFT', 16#98).
-define(              'RSHIFT', 16#99).
-define(             'BOOLAND', 16#9a).
-define(              'BOOLOR', 16#9b).
-define(            'NUMEQUAL', 16#9c).
-define(      'NUMEQUALVERIFY', 16#9d).
-define(         'NUMNOTEQUAL', 16#9e).
-define(            'LESSTHAN', 16#9f).
-define(         'GREATERTHAN', 16#a0).
-define(     'LESSTHANOREQUAL', 16#a1).
-define(  'GREATERTHANOREQUAL', 16#a2).
-define(                 'MIN', 16#a3).
-define(                 'MAX', 16#a4).
-define(              'WITHIN', 16#a5).

%% crypto
-define(           'RIPEMD160', 16#a6).
-define(                'SHA1', 16#a7).
-define(              'SHA256', 16#a8).
-define(             'HASH160', 16#a9).
-define(             'HASH256', 16#aa).
-define(       'CODESEPARATOR', 16#ab).
-define(            'CHECKSIG', 16#ac).
-define(      'CHECKSIGVERIFY', 16#ad).
-define(       'CHECKMULTISIG', 16#ae).
-define( 'CHECKMULTISIGVERIFY', 16#af).

%% reserved opcodes
-define(                'NOP1', 16#b0).
-define( 'CHECKLOCKTIMEVERIFY', 16#b1).
-define( 'CHECKSEQUENCEVERIFY', 16#b2).
-define(                'NOP4', 16#b3).
-define(                'NOP5', 16#b4).
-define(                'NOP6', 16#b5).
-define(                'NOP7', 16#b6).
-define(                'NOP8', 16#b7).
-define(                'NOP9', 16#b8).
-define(               'NOP10', 16#b9).
